### ISSUE TITLE
Bad Example Code

### ISSUE THREAD

**Issue by calebgrove** [zoltantothcom/vanilla-js-tabs#1]
On http://zoltantothcom.github.io/vanilla-js-tabs/, you have `var tabs = new Tab({...` in the example where it should be `var tabs = new Tabs({`.

BTW, thanks for this little library, it's exactly what I was looking for. :)

**Comment by zoltantothcom** [comment]
@CalebGrove Thanks for noticing the typo! And glad it was useful :)
