### ISSUE TITLE
Wrong openTab Default?

### ISSUE THREAD

**Issue by calebgrove** [zoltantothcom/vanilla-js-tabs#2]
So, line #20 of vanilla-js-tabs.js says `openTab = options.open || 1`. I'm no JS expert, but it seems that it should be `openTab = options.open || 0`. Unless I change the `1` to a `0`, it appears to be impossible to set `open` in the initialization script to the first tab, either by setting it's value to `0` or by simply not setting it. If I don't set it, it ends up selecting the second tab as the default.

Should I be creating a PR for this?

**Comment by zoltantothcom** [comment]
@CalebGrove Correct - it should be `|| 0`. You can absolutely create a PR with the fix if you wish.

**Comment by zoltantothcom** [comment]
@CalebGrove Thank you!
